### PR TITLE
Feature: Discharge during daytime

### PR DESCRIPTION
**Pull request by canbaytok**
Hi Reinhard,

first off huge thanks for this project! I installed my Zendure Hub 2000 with an AB2000 battery on saturday and have no complaints so far.
One thing I noticed yesterday was that the hub will not allow a discharge during daytime, causing the consumption from the grid to rise, while the battery has quite a lot of charge (e.g. when a cloud passes and solar power drops).
I implemented an additional flag to override the daytime check at [solarflow-control.py#L239](https://github.com/canbaytok/solarflow-control/blob/c64ad2349f3b86c7d17d88fadb9d1e133b078dc4/src/solarflow/solarflow-control.py#L239) as my nightly need for electricity is quite low and the battery does not need to be fully charged before the sun goes down.

Is this something you would be willing to merge into the main project? I also thought about adding a threshold value to the configuration, where the user can define the battery charge level after which a discharge during daytime is allowed (maybe even a hysteresis with configurations `allow_discharge_during_daytime_after = X%` and `disallow_discharge_during_daytime_after = X%`).

I would also add the necessary documentation to the README.md, before the branch merges (in case a small description is needed)

BR
Can

### CODE REVIEW

**Comment by canbaytok** [comment]
Forgot to mention it: I am testing the code and do not see any issues so far. The hub stops charging the battery and starts providing additional energy to the microinverter, when solar power drops, while demand stays constant.
What I can't test is a setup where panels are also directly connected to the microinverter. I don't see any reason, why the change would affect this, but I'm not 100% certain

**Comment by reinhard-brandstaedter** [comment]
Hi @canbaytok thanks for your contribution!
FYI: a day discharge can already be done today by adjusting the sunrise/sunset offset variables. Those define the timeframe after sunrise and before sunset in which the battery can discharge. if you set them big enough (so that they actually overlap at noon) you get a discharge throughout the day.

**Comment by tuxianerDE** [comment]
@reinhard-brandstaedter may be the solution of @canbaytok  is a more elegant way for the "I am on vacation scenario" that is also mentioned in the #80 topic?

@canbaytok  would it be possible to expose this variable and make it MQTT controllable? @reinhard-brandstaedter this way you can leave your default sunrise/sunset values as is (may be summer/winter adjustment) but otherwise steer this behavior via a button/automation in HA without the need to go into the config and restart the container.

**Comment by canbaytok** [comment]
Hi everyone,

@reinhard-brandstaedter setting the sunrise/sunset_offsets really high was also the first solution I could come up with (I'm lazy and prefer not to change the source code 😂), but it felt kind of wrong to misuse the values like that and my understanding was, that the solar bypass would never be turned on, because the controller was always in "night" mode.

After reviewing the code a bit more now, I saw that the bypass is controlled by [solarflow.py#L156](https://github.com/canbaytok/solarflow-control/blob/c64ad2349f3b86c7d17d88fadb9d1e133b078dc4/src/solarflow/solarflow.py#L156), which turns it on and [solarflow-control.py#L220](https://github.com/canbaytok/solarflow-control/blob/c64ad2349f3b86c7d17d88fadb9d1e133b078dc4/src/solarflow/solarflow-control.py#L220), which would immediately turn it off, as soon as demand should exceed the available solarpower. This behavior can occur once every day, as solarflow-control allows itself to control the bypass again after sunrise.

With this fact in mind, I would definitly prefer my implementation as a discharge is allowed during daytime, but it doesn't affect the bypass control in any way.

@tuxianerDE I'm guessing controlling this value via MQTT/Home Assistant shouldn't be too hard, as it would basically be a switch like the "Buzzer" and "Automatic Bypass recovery" switches.

**Comment by reinhard-brandstaedter** [comment]
I'm wondering if dropping the sunrise/sunset offset completely in favour of a SoC-based day-discharge allowance would make sense actually.
e.g. allow day discharge
after sunrise discharging is possible if the battery is higher than X%
before sunset dischargin is possible if the battery is higher than Y% but not if it is lower than X%

but in X and Y must not be too close to avoid jumping between charging/discharging all the time (and thus driving inverter limit adjustments crazy.
And it should go in accordance with min_charge_levels also .

**Comment by tuxianerDE** [comment]
Well dropping the sunrise/sunset parameters might be a consideration (none I would take lightly) however given that the SoC value are in my view still unreliable the approach taken with the "simple" switch would allow to maintain the sunrise/sunset (+offset) logic for the normal operations whilst allowing for more "quieter" time i.e. "I am not home for long just cover my demand all day" is covered.

Plugging in a logic for battery use based on the SoC I would consider a rather larger undertaking that requires us to believe in the SoC values

**Comment by canbaytok** [comment]
@tuxianerDE I'll try to implement the control over the weekend and test it in my own solarflow-control instance

@reinhard-brandstaedter Thanks for merging!
I will also update the `README.md` to explain the configuration option a little bit

**Pull request merged**
